config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'goodies#home'

  get 'about' => 'goodies#about'
  get 'statistics' => 'goodies#statistics'

  post 'create_user' => 'users#create', as: :create_user
  resources :users, except: :create do
    resources :ideas, only: :index
  end

  resources :books, except: :show
  get 'loans' => 'books#outstanding_loans', as: :outstanding_loans
  get 'recent/new' => 'books#recently_created', as: :recently_created
  get 'recent/updated' => 'books#recently_updated', as: :recently_updated

  resources :collections, :languages, :publishers, :categories, :users, :genres, :colors, except: :show do
    resources :books, only: :index
  end

  resources :ideas, except: :show

  get 'google/search' => 'google#search'

  get 'amazon/search' => 'amazon#search'
  get 'amazon/robot' => 'amazon#robot'
  post 'amazon' => 'amazon#add_amazon_details', as: :add_amazon
  delete 'amazon/:id' => 'books#remove_amazon_details', as: :remove_amazon

  get 'backups' => 'backups#show'
  get 'backup/:file' => 'backups#download_sql', as: :download_sql
  get 'backup/zip/:file' => 'backups#download_zip', as: :download_zip
  post 'backup' => 'backups#new', as: :new_backup
  delete 'backup' => 'backups#remove', as: :remove_backup

  match "*path" => redirect('/'), via: :all
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :books

  validates :name, presence: true

  after_destroy :reassign_books

  private

  def reassign_books
    Book
      .where(collection_id: id)
      .update_all(collection_id: nil) unless books.empty?
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @total_book_count = Book.all.size
    @collections = Collection.page(params[:page]).per(APP_CONFIG['max_rows']).order('name ASC')
    if params[:q]
      @collections = @collections.where(["name LIKE ? OR description LIKE ?", params[:q], params[:q]])
    end
  end

  def show
  end

  def new
    @collection = Collection.new
  end

  def edit
  end

  def create
    @collection = Collection.new(collection_params)
    respond_to do |format|
      if @collection.save
        format.html { redirect_to edit_collection_path(@collection), notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to edit_collection_path(@collection), notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: collections_url, notice: 'Collection was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_collection
    @collection = Collection.find(params[:id])
  end

  def collection_params
    params.require(:collection).permit(:name, :description)
  end
end

app/views/collections/_form.html.erb
<%= simple_form_for @collection, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>

  <%= f.error_notification %>

  <%= f.input :name, label: 'Collection', autofocus: true %>
  <%= f.input :description, as: :text %>
  <%= f.submit "Save", class: "btn btn-success" %>

<% end %>

app/views/collections/edit.html.erb
<% provide(:title, "Edit Collection") %>

<%= pretty_timestamp(@collection, 'collection') %>

<%= render 'form' %>

app/views/collections/index.html.erb
<% provide(:title, "Manage Collections") %>

<table class="table table-hover table-striped table-condensed">
  <thead>
  <tr>
    <th>Collection</th>
    <th>Description</th>
    <th>Number of books</th>
    <th>Last updated</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @collections.each do |collection| %>
    <tr>
      <td><b><%= link_to collection.name, edit_collection_path(collection) %></b></td>
      <td><%= collection.description %></td>
      <td><%= pluralize(collection.books.size, 'book') %>
        (<%= number_to_percentage(collection.books.size.to_f / @total_book_count * 100, precision: 1) %>)
      </td>
      <td><%= timestamp(collection.updated_at) %></td>
      <td>
        <%= link_to t('.show', :default => t("helpers.links.show")),
                    collection_books_path(collection), :class => 'btn btn-default btn-xs' %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_collection_path(collection), :class => 'btn btn-primary btn-xs' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    collection,
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-danger btn-xs' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @collections %>

<br/>

<%= link_to 'New Collection', new_collection_path, class: 'btn btn-default' %>

app/views/collections/new.html.erb
<% provide(:title, "New Collection") %>

<%= render 'form' %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>