config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'goodies#home'

  get 'about' => 'goodies#about'
  get 'statistics' => 'goodies#statistics'

  post 'create_user' => 'users#create', as: :create_user
  resources :users, except: :create do
    resources :ideas, only: :index
  end

  resources :books, except: :show
  get 'loans' => 'books#outstanding_loans', as: :outstanding_loans
  get 'recent/new' => 'books#recently_created', as: :recently_created
  get 'recent/updated' => 'books#recently_updated', as: :recently_updated

  resources :collections, :languages, :publishers, :categories, :users, :genres, :colors, except: :show do
    resources :books, only: :index
  end

  resources :ideas, except: :show

  get 'google/search' => 'google#search'

  get 'amazon/search' => 'amazon#search'
  get 'amazon/robot' => 'amazon#robot'
  post 'amazon' => 'amazon#add_amazon_details', as: :add_amazon
  delete 'amazon/:id' => 'books#remove_amazon_details', as: :remove_amazon

  get 'backups' => 'backups#show'
  get 'backup/:file' => 'backups#download_sql', as: :download_sql
  get 'backup/zip/:file' => 'backups#download_zip', as: :download_zip
  post 'backup' => 'backups#new', as: :new_backup
  delete 'backup' => 'backups#remove', as: :remove_backup

  match "*path" => redirect('/'), via: :all
end

app/models/color.rb
class Color < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: %i(slugged finders)

  has_many :books

  validates :name, presence: true
  validates :hex_code, presence: false, format: {
    with: %r{^#(([0-9a-fA-F]{2}){3}|([0-9a-fA-F]){3})$},
    multiline: true
  }

  after_destroy :reassign_books
  before_save :downcase_hex_code

  def should_generate_new_friendly_id?
    name_changed?
  end

  private

  def reassign_books
    Book
      .where(color_id: id)
      .update_all(color_id: nil) unless books.empty?
  end

  def downcase_hex_code
    hex_code.downcase!
  end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :set_color, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @total_book_count = Book.all.size
    @colors = Color.page(params[:page]).per(APP_CONFIG['max_rows']).order('name ASC')
    if params[:q]
      @colors = @colors.where('(name LIKE ? OR description LIKE ?)', "%#{params[:q]}%", "%#{params[:q]}%")
    end
  end

  def show
  end

  def new
    @color = Color.new
  end

  def edit
  end

  def create
    @color = Color.new(color_params)
    respond_to do |format|
      if @color.save
        format.html { redirect_to edit_color_path(@color), notice: 'Color was successfully created.' }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to edit_color_path(@color), notice: 'Color was successfully updated.' }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @color.destroy
    respond_to do |format|
      format.html { redirect_to edit_color_path(@color), notice: 'Color was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_color
    @color = Color.find(params[:id])
  end

  def color_params
    params.require(:color).permit(:name, :description, :hex_code)
  end
end

app/views/colors/_form.html.erb
<%= simple_form_for @color, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>

  <%= f.error_notification %>

  <%= f.input :name, label: 'Color', autofocus: true %>
  <%= f.input :hex_code, placeholder: 'e.g. #cc0000' %>
  <%= f.input :description, as: :text %>

  <%= f.submit "Save", class: "btn btn-success" %>

<% end %>

<% if @color.hex_code? %>

  <hr/>

  <div style="color: <%= @color.hex_code %>; font-weight: bold; font-size: 18px">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ullamcorper sem at interdum sagittis.
      Vestibulum egestas feugiat dolor at sodales. Curabitur enim est, venenatis at bibendum eu, venenatis pharetra
      nisl. Suspendisse potenti. Etiam id finibus sapien. Suspendisse ut risus eget leo ultrices suscipit vel nec
      nulla. Nunc risus nisi, lobortis in pulvinar sed, sagittis ut mi.</p>
    <p>Proin eleifend turpis eget aliquam molestie. Integer commodo sed ligula non porttitor. Phasellus tincidunt a
      tortor vitae cursus. Integer interdum magna in mi viverra, non aliquet mauris dictum. Maecenas at rutrum felis,
      at iaculis tortor. Fusce id enim hendrerit, viverra ipsum quis, dictum nunc. Etiam lectus sapien, accumsan sit
      amet sapien in, dictum euismod tortor. Maecenas placerat nulla non enim hendrerit rutrum. Quisque ac orci eros.
      Vivamus elementum malesuada ante, a vehicula est commodo nec.</p>
  </div>

  <hr/>

<% end %>

app/views/colors/edit.html.erb
<% provide(:title, 'Edit Color') %>

<%= pretty_timestamp(@color, 'color') %>

<%= render 'form' %>

app/views/colors/index.html.erb
<% provide(:title, "Manage Colors") %>

<table class="table table-hover table-striped table-condensed">
  <thead>
  <tr>
    <th>Color</th>
    <th>Description</th>
    <th>Hex Code</th>
    <th>Number of books</th>
    <th>Last updated</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @colors.each do |color| %>
    <tr>
      <td><b><%= link_to color.name, edit_color_path(color) %></b></td>
      <td><%= color.description %></td>
      <td><%= content_tag(:span, color.hex_code, style: "font-weight: bold; color: " + color.hex_code) if color.hex_code? %></td>
      <td><%= pluralize(color.books.size, 'book') %>
        (<%= number_to_percentage(color.books.size.to_f / @total_book_count * 100, precision: 1) %>)
      </td>
      <td><%= timestamp(color.updated_at) %></td>
      <td>
        <%= link_to t('.show', :default => t("helpers.links.show")),
                    color_books_path(color), :class => 'btn btn-default btn-xs' %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_color_path(color), :class => 'btn btn-primary btn-xs' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    color,
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-danger btn-xs' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @colors %>

<br/>

<%= link_to 'New Color', new_color_path, class: 'btn btn-default' %>

app/views/colors/new.html.erb
<% provide(:title, "New Color") %>

<%= render 'form' %>

app/views/colors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @color.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @color.description %>
</p>

<%= link_to 'Edit', edit_color_path(@color) %> |
<%= link_to 'Back', colors_path %>