config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'goodies#home'

  get 'about' => 'goodies#about'
  get 'statistics' => 'goodies#statistics'

  post 'create_user' => 'users#create', as: :create_user
  resources :users, except: :create do
    resources :ideas, only: :index
  end

  resources :books, except: :show
  get 'loans' => 'books#outstanding_loans', as: :outstanding_loans
  get 'recent/new' => 'books#recently_created', as: :recently_created
  get 'recent/updated' => 'books#recently_updated', as: :recently_updated

  resources :collections, :languages, :publishers, :categories, :users, :genres, :colors, except: :show do
    resources :books, only: :index
  end

  resources :ideas, except: :show

  get 'google/search' => 'google#search'

  get 'amazon/search' => 'amazon#search'
  get 'amazon/robot' => 'amazon#robot'
  post 'amazon' => 'amazon#add_amazon_details', as: :add_amazon
  delete 'amazon/:id' => 'books#remove_amazon_details', as: :remove_amazon

  get 'backups' => 'backups#show'
  get 'backup/:file' => 'backups#download_sql', as: :download_sql
  get 'backup/zip/:file' => 'backups#download_zip', as: :download_zip
  post 'backup' => 'backups#new', as: :new_backup
  delete 'backup' => 'backups#remove', as: :remove_backup

  match "*path" => redirect('/'), via: :all
end

app/controllers/backups_controller.rb
require 'open3'

class BackupsController < ApplicationController
  before_action :authenticate_user!

  def show
    @files = Dir.glob(File.join(BACKUP_FOLDER, '*.sql'))
  end

  def new
    config = ActiveRecord::Base.connection_db_config.configuration_hash
    if Rails.env == 'production'
      database = config[:database]
      username = config[:username]
      timestamp = Time.now.strftime('%Y-%m-%d_%H-%M-%S')
      command = "mysqldump -u #{username} #{database} -p > " + File.join(BACKUP_FOLDER, "#{database}-#{timestamp}.sql")
      stdin, stdout, _stderr = Open3.popen3(command)
      stdin.puts(config[:password])
      if stdout.gets.nil?
        flash[:success] = 'The new backup has been launched.'
      else
        flash[:error] = "Oops, something went wrong. The console returned an error message: #{stdout.gets}"
      end
    else
      flash[:warning] = 'WARNING: The database backup tool is only available in a production environment.'
    end
    redirect_back fallback_location: { action: 'show' }
  end

  def remove
    if File.delete(params[:file])
      pretty = File.basename(params[:file])
      flash[:success] = "The backup file (#{pretty}) has been deleted."
    else
      flash[:warning] = 'There may have been a problem deleting the selected file. Please try again later.'
    end
    redirect_back fallback_location: { action: 'show' }
  end

  def download_sql
    filename = "#{params[:file]}.sql"
    file = File.join(BACKUP_FOLDER, filename)
    send_data File.read(file), disposition: 'attachment', filename: filename, type: 'text/plain'
  end

  def download_zip
    filename = "#{params[:file]}.sql"
    file = File.join(BACKUP_FOLDER, filename)
    send_data compress(File.read(file)), disposition: 'attachment', filename: "#{params[:file]}.zip", type: 'application/zip'
  end

  private

  def compress(data)
    ActiveSupport::Gzip.compress data
  end

end

app/views/backups/show.html.erb
<% provide(:title, "Database Backup") %>

<p>You can create, browse, and download database backup files here.</p>

<p>There are currently <%= @files.count %> backup(s) available.</p>

<% if @files.count > 0 %>

  <table class="table table-hover table-striped table-condensed">
    <thead>
    <tr>
      <th>Backup file</th>
      <th>File type</th>
      <th>File size</th>
      <th>Creation time</th>
      <th>Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @files.each do |file| %>
      <tr>
        <td><%= image_tag 'icon_sql.png', size: 20 %> <b><%= link_to File.basename(file), download_sql_path(file: File.basename(file)) %></b></td>
        <td><%= File.extname(file) %></td>
        <td><%= Filesize.from(File.stat(file).size.to_s + ' B').pretty %></td>
        <td><%= timestamp(File.ctime(file)) %></td>
        <td>
          <%= link_to 'Download',
                      download_sql_path(file: File.basename(file)),
                      :class => 'btn btn-default btn-xs' %>
          <%= link_to 'Compress',
                      download_zip_path(file: File.basename(file)),
                      :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      remove_backup_path(file: file),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

<% end %>

<% if Rails.env == 'production' %>
  <br />
  <%= link_to 'New Backup', new_backup_path, class: 'btn btn-default', method: :post, :data => { :confirm => 'Are you sure?' } %>
<% end %>