config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'goodies#home'

  get 'about' => 'goodies#about'
  get 'statistics' => 'goodies#statistics'

  post 'create_user' => 'users#create', as: :create_user
  resources :users, except: :create do
    resources :ideas, only: :index
  end

  resources :books, except: :show
  get 'loans' => 'books#outstanding_loans', as: :outstanding_loans
  get 'recent/new' => 'books#recently_created', as: :recently_created
  get 'recent/updated' => 'books#recently_updated', as: :recently_updated

  resources :collections, :languages, :publishers, :categories, :users, :genres, :colors, except: :show do
    resources :books, only: :index
  end

  resources :ideas, except: :show

  get 'google/search' => 'google#search'

  get 'amazon/search' => 'amazon#search'
  get 'amazon/robot' => 'amazon#robot'
  post 'amazon' => 'amazon#add_amazon_details', as: :add_amazon
  delete 'amazon/:id' => 'books#remove_amazon_details', as: :remove_amazon

  get 'backups' => 'backups#show'
  get 'backup/:file' => 'backups#download_sql', as: :download_sql
  get 'backup/zip/:file' => 'backups#download_zip', as: :download_zip
  post 'backup' => 'backups#new', as: :new_backup
  delete 'backup' => 'backups#remove', as: :remove_backup

  match "*path" => redirect('/'), via: :all
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: %i(slugged finders)

  has_many :books

  validates :name, presence: true, uniqueness: true

  before_destroy :reassign_books

  def should_generate_new_friendly_id?
    name_changed?
  end

  private

  def reassign_books
    if name == DEFAULT_CATEGORY[:name]
      false
    else
      Book
        .where(category_id: id)
        .update_all(category_id: default_category) unless books.empty?
    end
  end

  def default_category
    category = Category.find_by(DEFAULT_CATEGORY)
    if category.nil?
      Category.create(DEFAULT_CATEGORY).id
    else
      category.id
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @total_book_count = Book.all.size
    @categories = Category.page(params[:page]).per(APP_CONFIG['max_rows']).order('name ASC')
    if params[:q]
      @categories = @categories.where('(name LIKE ? OR description LIKE ?)', "%#{params[:q]}%", "%#{params[:q]}%")
    end
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to edit_category_path(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to edit_category_path(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: categories_url, notice: 'Category was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/views/categories/_form.html.erb
<%= simple_form_for @category, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>

  <%= f.error_notification %>

  <%= f.input :name, label: 'Category', autofocus: true %>
  <%= f.input :description %>

  <%= f.submit "Save", class: "btn btn-success" %>

<% end %>

app/views/categories/edit.html.erb
<% provide(:title, "Edit Category") %>

<%= pretty_timestamp(@category, 'category') %>

<%= render 'form' %>

app/views/categories/index.html.erb
<% provide(:title, "Manage Categories") %>

<table class="table table-hover table-striped table-condensed">
  <thead>
  <tr>
    <th>Category</th>
    <th>Description</th>
    <th>Number of books</th>
    <th>Last updated</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td><b><%= link_to category.name, edit_category_path(category) %></b></td>
      <td><%= category.description %></td>
      <td><%= pluralize(category.books.size, 'book') %>
        (<%= number_to_percentage(category.books.size.to_f / @total_book_count * 100, precision: 1) %>)
      </td>
      <td><%= timestamp(category.updated_at) %></td>
      <td>
        <%= link_to t('.show', :default => t("helpers.links.show")),
                    category_books_path(category), :class => 'btn btn-default btn-xs' %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_category_path(category), :class => 'btn btn-primary btn-xs' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    category,
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-danger btn-xs' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @categories %>

<br/>

<%= link_to 'New Category', new_category_path, class: 'btn btn-default' %>

app/views/categories/new.html.erb
<% provide(:title, "New Category") %>

<%= render 'form' %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>